### ISSUE TITLE
OTAA device and join request

### ISSUE THREAD

**Issue by Gillani0** [houluy/lora-motes-emulator#2]
Hi,
I'm having some trouble to create an OTAA device and send a join request. Apparently there's only the ABP command available to create  ABP compliant device. Can you please help me in this matter. Cheers

Syed

**Comment by houluy** [comment]
hi, would u provide some details?

What happens exactly? Which LoRaWAN verison were u using? Which LoRa server is used?

**Comment by Gillani0** [comment]
Hi,

I'm using LoRaWAN 1.0, when I tried to create the device with the new command and join type:

`pipenv run python main.py -n join`

I always gets the error:  `ERROR - You need to finish Join procedure before sending application data` and nothing is received on the UDP port.

However, it should send a join request to the server.

**Comment by houluy** [comment]
I guess the problem is that the `config/device.yml` is not properly configured, an example looks like this,

```yaml
Device:
    JoinEUI: '0000000000000000'
    DevEUI: '1234567890ABCDEF'
Keys:
    AppKey: 4c0892904bb3544138b5070c5c4069cd
    NwkKey: be60e113de86d73b52fc0005bf5d89e8
Gateway:
    GatewayEUI: 4e7b2799b9bfd427
```

If you're using LoRaWAN 1.0.2, change the `AppEUI` to `JoinEUI`, and make `NwkKey` field equal to `AppKey` field. However, LoRaWAN 1.0.2 is not well tested, it may have some compatibility issues.

There is an older commit that may work well with LoRaWAN 1.0.2, check this commit if you need:
```
72b776071bf9329e5a9481a868b35f75d90b5d44
commit message: update pyyaml version
```
